# Generated by Django 5.1.5 on 2025-02-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdailydrink', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwaterintake',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
